### ISSUE TITLE
the path arg is not read and only the defaultFilePath is used

### ISSUE THREAD

**Issue by bmarchand-altima** [p-balu/ghore#3]
environnement : windows 10

ghore is launched from command line : 

`npm start "file.md"`

only the file `README.md` is read

i have to change 
`const path = process.argv[3] || defaultFilePath;`
to
`const path = process.argv[2] || defaultFilePath;`

in the file server.js of the root

to be able to start the file i want

and very good job :) for all :)

**Comment by valorisa** [comment]
Hello,

A simple question : how did you go about installing ghore on Windows 10 ? By following the procedure for Linux and macOS ? I haven't been able to do this since Windows 11 Enterprise. However, nodejs is perfectly functional and I followed the guide to the nearest comma.
Thanks in advance..

**Comment by bmarchand-altima** [comment]
What i did:

1. i haven't read the installation tips so i installed ghore with npm
`npm install ghore`

2. i followed the installation steps

># Clone the repository
>git clone https://github.com/p-balu/ghore.git

># Navigate to the project directory
>cd ghore

># Install dependencies
>npm install

>#To start the application locally
>npm start `your/filepath/other_file.md`

**Comment by p-balu** [comment]
> Hello,
> 
> A simple question : how did you go about installing ghore on Windows 10 ? By following the procedure for Linux and macOS ? I haven't been able to do this since Windows 11 Enterprise. However, nodejs is perfectly functional and I followed the guide to the nearest comma. Thanks in advance..

So, the package installation is having an issue with Windows 11 as one of the packages called cmark-gfm I am using, the developers stopped contributing to it and is compatible only till windows 10 that's one of the reason @bmarchand-altima was able to install and use it successfully in windows 10. I need to take some time to look into the cmark-gfm package make those changes to successfully work in windows 11.

**Comment by p-balu** [comment]
> environnement : windows 10
> 
> ghore is launched from command line :
> 
> `npm start "file.md"`
> 
> only the file `README.md` is read
> 
> i have to change `const path = process.argv[3] || defaultFilePath;` to `const path = process.argv[2] || defaultFilePath;`
> 
> in the file server.js of the root
> 
> to be able to start the file i want
> 
> and very good job :) for all :)

Thanks for using the tool. I will have a look at it as I remember I have handled it correctly will have a look at it again. Glad you liked it, and enjoy using the tool.

**Comment by valorisa** [comment]
Thanks for all responses.

**Comment by valorisa** [comment]
> > Hello,
> > A simple question : how did you go about installing ghore on Windows 10 ? By following the procedure for Linux and macOS ? I haven't been able to do this since Windows 11 Enterprise. However, nodejs is perfectly functional and I followed the guide to the nearest comma. Thanks in advance..
> 
> So, the package installation is having an issue with Windows 11 as one of the packages called cmark-gfm I am using, the developers stopped contributing to it and is compatible only till windows 10 that's one of the reason @bmarchand-altima was able to install and use it successfully in windows 10. I need to take some time to look into the cmark-gfm package make those changes to successfully work in windows 11.


So this can be useful to other Windows users who need to use Ghore. Thanks for your time.

**Comment by valorisa** [comment]
> What i did:
> 
> 1. i haven't read the installation tips so i installed ghore with npm
>    `npm install ghore`
> 2. i followed the installation steps
> 
> > # Clone the repository
> > git clone https://github.com/p-balu/ghore.git
> 
> > # Navigate to the project directory
> > cd ghore
> 
> > # Install dependencies
> > npm install
> 
> > #To start the application locally
> > npm start `your/filepath/other_file.md`

Same procedure in my case.
